Add linear api in docs
JuliaSmoothOptimizers/NLPModels.jl pull request #383
Opened 2021-12-13 20:31 UTC by tmigot

Modify the doc following #379 #377

2021-12-13 20:40 UTC, abelsiqueira requested changes
Thanks for the quick PR.

2021-12-13 20:51 UTC, tmigot commented on docs/src/guidelines.md
> +  - `jtprod_nln!(nlp, x, v, Jtv)`
In theory no, for instance [L.57](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/blob/289b81ceea0961cb60a6e536d32311114b09405b/src/nlp/api.jl#L57), it doesn't call `cons_lin` (resp. `cons_nln`) if you have no linear (resp. nonlinear) constraints.

2021-12-13 21:10 UTC, abelsiqueira commented on docs/src/guidelines.md
> +  - `jtprod_nln!(nlp, x, v, Jtv)`
That's the second situation in my list, you have to make sure that `nlp.meta.lin = []`. My first comment ("the default will error") is not totally accurate, but the additional information still applies.

2021-12-13 21:26 UTC, abelsiqueira commented on docs/src/guidelines.md
> +  - `jtprod_nln!(nlp, x, v, Jtv)`
Yes, I think something like "`cons_nln!(...)` and `cons_lin!(...)`", and then after the list is complete, we add disclaimers like "Notice that if you need to define the linear constraints by using `nlp.meta.lin`. If your model doesn't differentiate between linear and nonlinear constraints you can define only the `*_nln!` variants above, or alternatively, the functions without the suffixes `_nln!` (e.g., only `cons!`)."

2021-12-14 01:06 UTC, tmigot commented on docs/src/guidelines.md
> +  - `jtprod_nln!(nlp, x, v, Jtv)`
Ok, I tried a new version. Let me know what you think.

2021-12-14 08:12 UTC, abelsiqueira approved these changes
Looks good to me!

2021-12-14 08:13 UTC, merged

2021-12-14 08:13 UTC, abelsiqueira commented
Thanks