add blocknlpmodels in the docs
JuliaSmoothOptimizers/NLPModels.jl pull request #439
Opened 2023-05-30 20:19 UTC by grishabh147

Added details of `BlockNLPModels.jl` and `BlockNLPAlgorithms.jl` that implement `NLPModels.jl`'s API in the documentation.

2023-06-19 19:59 UTC, tmigot requested changes
Hey @grishabh147 !
Thank you for the PR, and very sorry to take such a long time before reviewing it.
I suggested removing the link to BlockNLPAlgorithms.jl as this is more a list of models than solver. But, I will definitely keep it in mind when creating a similar list for solvers.

Any plan to make the package a Julia registered package?

2023-06-19 19:59 UTC, tmigot commented on docs/src/models.md
> +- [BlockNLPAlgorithms.jl](https://github.com/exanauts/BlockNLPAlgorithms.jl): Implements popular decomposition algorithms such as dual decomposition and ADMM to solve block strucutred NLPs.
```suggestion
```

2023-06-19 19:59 UTC, tmigot commented on docs/src/models.md
> +- [BlockNLPModels.jl](https://github.com/exanauts/BlockNLPModels.jl): For modeling block structured nonlinear optimization problems
```suggestion
- [BlockNLPModels.jl](https://github.com/exanauts/BlockNLPModels.jl): For modeling block structured nonlinear optimization problems.
```

2023-07-14 18:03 UTC, grishabh147 commented
Hi @tmigot, I have made the requested changes, thanks for reviewing this pull-request.

Yes, there are plans to make this a registered package, however, we intend to do that once we have a better front-end for this. We are planning to integrate this with [Plasmo.jl](https://github.com/plasmo-dev/Plasmo.jl).

2023-07-14 19:03 UTC, tmigot approved these changes
LGTM, Thank you @grishabh147

2023-07-14 19:35 UTC, merged