Remove `Vector` implicit assumption
JuliaSmoothOptimizers/NLPModels.jl pull request #455
Opened 2024-03-26 20:43 UTC by tmigot

In some places, we assume that the vectors are of type `Vector{T}` which is not necessary the case in practice.

Connected to #454

2024-04-01 14:49 UTC, tmigot commented
Breakage:
- [ ] https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/tree/avoid-sim fixes ADNLPModels
- [ ] https://github.com/JuliaSmoothOptimizers/SolverTest.jl/issues/64

2024-04-09 14:40 UTC, amontoison approved these changes

2024-04-19 19:43 UTC, abelsiqueira approved these changes
Thanks!

2024-04-20 14:42 UTC, dpo requested changes
Much cleaner, thank you! Just one minor comment, and the PR can be merged.

2024-04-20 14:42 UTC, dpo commented on src/nlp/api.jl
> +  c = nlp.meta.ncon > 0 ? cons(nlp, x) : S(undef, 0)
```suggestion
  c = cons(nlp, x)
```
`cons()` already does the right thing here.

2024-04-23 11:21 UTC, merged